(dp1
S'output'
p2
S"<type 'exceptions.OSError'> ./libmeme.so: cannot open shared object file: No such file or directory"
p3
sS'layer'
p4
S'/vagrant/web2py/applications/memegenerator/models/test.py'
p5
sS'code'
p6
S'import ctypes\n\nlib = ctypes.CDLL(\'./libmeme.so\')\npfun = lib.makeMeme\nx = pfun(ex.jpg, ex1.jpg, \'blabla\')\nprint "Success!"\n'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/vagrant/web2py/gluon/restricted.py", line 227, in restricted\n    exec ccode in environment\n  File "/vagrant/web2py/applications/memegenerator/models/test.py", line 3, in <module>\n    lib = ctypes.CDLL(\'./libmeme.so\')\n  File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in __init__\n    self._handle = _dlopen(self._name, mode)\nOSError: ./libmeme.so: cannot open shared object file: No such file or directory\n'
p11
s.